### ISSUE TITLE
Layout failure during deployment

### ISSUE THREAD

**Issue by Syifaa27** [TegarAditya/fluidiatest-admin#1]
The landing page layout becomes messy when deployed to the server. Does this have anything to do with the docker image?

![messy layout](https://github.com/user-attachments/assets/0ca7e901-4f61-4835-a9bb-c73580fca6c0)

**Comment by TegarAditya** [comment]
try running `bun run build` after deployment.

**Comment by Syifaa27** [comment]
ok, i'll try

**Comment by TegarAditya** [comment]
solved with cff38e33262f7fe110359541cf326119a4e62663
